"""Generated by eglot-typescript-preset."""

import os
from typing import Any, cast

from rassumfrassum.frassum import DirectResponse, LspLogic, Server
from rassumfrassum.json import JSON
from rassumfrassum.util import dmerge

SERVERS: list[list[str]] = __SERVERS__  # type: ignore[name-defined]
INIT_OPTIONS: dict[str, Any] | None = __INIT_OPTIONS__  # type: ignore[name-defined]
ESLINT_LOGIC: bool = __ESLINT_LOGIC__  # type: ignore[name-defined]


def _server_kind(name: str) -> str | None:
    base = name.lower().split("#", 1)[0]
    if "." in base:
        base = base.rsplit(".", 1)[0]
    if base in ("astro-ls", "astro-language-server"):
        return "astro-ls"
    if base == "biome":
        return "biome"
    if base == "deno":
        return "deno"
    if base in ("eslint", "eslint-language-server",
                "vscode-eslint-language-server"):
        return "eslint"
    if base == "oxfmt":
        return "oxfmt"
    if base == "oxlint":
        return "oxlint"
    if base == "tailwindcss-language-server":
        return "tailwindcss-language-server"
    if base in ("typescript-language-server", "tsserver"):
        return "typescript-language-server"
    if base in ("vscode-css-language-server", "css-language-server",
                "css-languageserver"):
        return "vscode-css-language-server"
    if base in ("vue-language-server", "@vue/language-server"):
        return "vue-language-server"
    return None


def _find_workspace_folder(scope_uri: str) -> dict | None:
    """Find workspace folder by searching for package.json from scopeUri."""
    if not scope_uri.startswith("file://"):
        return None

    file_path = scope_uri[7:]
    current_dir = os.path.dirname(file_path)

    while current_dir and current_dir != "/":
        if os.path.exists(os.path.join(current_dir, "package.json")):
            return {
                "uri": f"file://{current_dir}",
                "name": os.path.basename(current_dir),
            }
        parent = os.path.dirname(current_dir)
        if parent == current_dir:
            break
        current_dir = parent

    return None


def _eslint_config(workspace_folder: dict | None = None) -> dict:
    """Return base ESLint configuration."""
    config: dict[str, Any] = {
        "validate": "probe",
        "problems": {},
        "rulesCustomizations": [],
        "nodePath": None,
    }
    if workspace_folder:
        config["workspaceFolder"] = workspace_folder
    return config


class GeneratedTypeScriptLogic(LspLogic):
    def process_request(
        self, method: str, params: JSON, server: Server
    ) -> None:
        if method == "initialize" and INIT_OPTIONS and server == self.primary:
            params["initializationOptions"] = dmerge(
                params.get("initializationOptions") or {},
                INIT_OPTIONS,
            )
        super().process_request(method, params, server)

    async def on_server_notification(
        self, method: str, params: JSON, source: Server
    ) -> None:
        if (
            method == "tsserver/request"
            and _server_kind(source.name) == "vue-language-server"
        ):
            req = params[0] if isinstance(params, list) else None
            req_id = req[0] if isinstance(req, list) else None
            if req_id is not None:
                await self.notify_server(
                    source, "tsserver/response", [[req_id, None]]
                )
            return
        await super().on_server_notification(method, params, source)

    async def on_server_request(
        self, method: str, params: JSON, source: Server
    ) -> DirectResponse | None:
        result = await super().on_server_request(method, params, source)
        if result is not None:
            return result
        if method == "client/registerCapability":
            unsupported = {
                "workspace/didChangeWatchedFiles",
                "workspace/didChangeWorkspaceFolders",
            }
            regs = params.get("registrations", [])
            if regs and all(
                reg.get("method") in unsupported for reg in regs
            ):
                return DirectResponse(payload={})
        return None

    async def on_client_response(
        self,
        method: str,
        request_params: JSON,
        response_payload: JSON,
        is_error: bool,
        server: Server,
    ) -> None:
        if method == "workspace/configuration" and not is_error:
            req_items = request_params.get("items", [])
            res_items = cast(list[Any], response_payload)
            if len(res_items) < len(req_items):
                res_items.extend([None] * (len(req_items) - len(res_items)))

            for i, item in enumerate(req_items):
                section = item.get("section", "")
                if res_items[i] is None and section:
                    if section in ("css", "less", "scss"):
                        res_items[i] = {
                            "lint": {"unknownAtRules": "ignore"},
                        }
                    else:
                        res_items[i] = {}
                if (
                    ESLINT_LOGIC
                    and section == ""
                    and "eslint" in server.name.lower()
                ):
                    wfolder = _find_workspace_folder(
                        item.get("scopeUri", "")
                    )
                    cfg = _eslint_config(wfolder)
                    if isinstance(res_items[i], dict):
                        res_items[i] = dmerge(res_items[i], cfg)
                    else:
                        res_items[i] = cfg

        await super().on_client_response(
            method,
            request_params,
            response_payload,
            is_error,
            server,
        )


def servers():
    return SERVERS


def logic_class():
    return GeneratedTypeScriptLogic
